### ISSUE TITLE
关于采集后的数据处理请教

### ISSUE THREAD

**Issue by IHIDCHAOS** [thinkgos/gomodbus#3]
对于采集到的切片数据进行转换和缩放处理，例如[]byte转换为数据类型int8/16/32/64，uint8/16/32/64，float32/64等（包括多字节数据的大小端处理，高低位转换）；以及进行1倍，10倍，0.5倍，-10倍缩放数据。有什么比较好的措施吗？
我自己写了一部分转换，白天发出来请您指点。

**Comment by thinkgos** [comment]
切片数据转换,包括大小端处理,binary就可以处理了.
高低位转换,一般是整型数据高低位转换吧,这个math/bits可以处理.
数据缩放,没什么好的办法,转换完再进行缩放.

**Comment by JiajunDou** [comment]
Example:
```
func ReadConvert(data []byte)(ret int32) {
    buff := bytes.NewBuffer(data)
    binary.Read(buff, binary.BigEndian, &ret)
    return
}
```
You can change ret TYPE to get int32/16/uint32/16 ...

**Comment by IHIDCHAOS** [comment]
我把代码放在了https://gist.github.com/be4166c2f46124591157be56d549323e
用法是func Trans(buf []byte, v Map) (tmp interface{}, err error) {
	t := &Transform{}
	tValue := reflect.ValueOf(t)
	params := make([]reflect.Value, 2)
	params[0] = reflect.ValueOf(buf)
	params[1] = reflect.ValueOf(v.Scale)
	DT := strings.ToUpper(v.Datatype)
	if CheckDataTypeOK(DT) {
		tmp = tValue.MethodByName(DT).Call(params)[0].Interface()
		return tmp, err
	}
	return nil, errors.New(fmt.Sprint("transform datatype error: ", v.Datatype))
}

**Comment by thinkgos** [comment]
@IHIDCHAOS 打不开,看不懂啥意思

**Comment by JiajunDou** [comment]
> 我把代码放在了https://gist.github.com/be4166c2f46124591157be56d549323e
> 用法是func Trans(buf []byte, v Map) (tmp interface{}, err error) {
> t := &Transform{}
> tValue := reflect.ValueOf(t)
> params := make([]reflect.Value, 2)
> params[0] = reflect.ValueOf(buf)
> params[1] = reflect.ValueOf(v.Scale)
> DT := strings.ToUpper(v.Datatype)
> if CheckDataTypeOK(DT) {
> tmp = tValue.MethodByName(DT).Call(params)[0].Interface()
> return tmp, err
> }
> return nil, errors.New(fmt.Sprint("transform datatype error: ", v.Datatype))
> }

Good Job!

I think you can add some functions like Int64BEToBytes... for writing registers.

**Comment by IHIDCHAOS** [comment]
@thinkgos 利用反射调用不同数据类型对应的转换方法，传递数据和缩放两个参数，返回转换后的结果。gist无法访问的可以搜索添加hosts解决。

**Comment by thinkgos** [comment]
@IHIDCHAOS 这个是帮助性的功能函数. 主要是业务需求, .这个组帧其实没必要字节性拆分,.因为数据中没有string和切变这类变长数据. 你可以直接用binary的Read和Write,这个对定长数据直接struct与[]byte之间转换业务数据更快
