### ISSUE TITLE
寄存器的读取目前只支持uint16吗

### ISSUE THREAD

**Issue by yyn1110** [thinkgos/gomodbus#5]
您好，请问现在功能上是否还有缺失，例如寄存器的读取返回类型目前只支持整形，您有打算继续扩展其他的类型吗？

**Comment by thinkgos** [comment]
@yyn1110 不是都支持了么? 就bits和16-bits, 你说的其它类型,是应用层面的吧. 比如16-bits转uint32,int32,float32,float64等这些. 这些属应用层面,你可以使用官方binary包.

**Comment by thinkgos** [comment]
> 您好，请问现在功能上是否还有缺失，例如寄存器的读取返回类型目前只支持整形，您有打算继续扩展其他的类型吗？

功能层面,目前不支持ascii,rtu的服务端. 也不打算支持,在场合上,这两种类型99.99%是设备

**Comment by yyn1110** [comment]
好的，感谢您的回复。请问关于采集优化，例如按照地址排序，同时采集多个地址的数据这块您有打算支持吗？

**Comment by thinkgos** [comment]
@yyn1110  这是基础库,关于业务方面.不会支持.
 你可以参考下 [mb](https://github.com/thinkgos/mb)这个.
